"""add product_variants table

Revision ID: 07894704f59b
Revises: b47eac32f068
Create Date: 2026-01-30 21:27:13.764761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07894704f59b'
down_revision = 'b47eac32f068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))

    op.drop_table('product_variants')
    # ### end Alembic commands ###
