"""orders flow v1

Revision ID: b47eac32f068
Revises: 3b7de2e4aa7e
Create Date: 2026-01-08 18:06:10.260699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b47eac32f068'
down_revision = '3b7de2e4aa7e'
branch_labels = None
depends_on = None


def upgrade():
    # Old code commenting because we added new column with default value: at thsi time of creation existing rows will get default value 0
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('products', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))

    # New code to add column with default value:- we added this as on:- 08-01-2026
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'stock',
                sa.Integer(),
                nullable=False,
                server_default='0'
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('stock')

    # ### end Alembic commands ###
